/**
 * Stable, machine-readable error codes returned in API responses.
 * Mobile clients map these to localised, user-facing copy.
 *
 * NEVER rename an existing code — only add new ones.
 */
export const ErrorCode = {
  // Generic
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',

  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  SESSION_REVOKED: 'SESSION_REVOKED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  PHONE_NOT_VERIFIED: 'PHONE_NOT_VERIFIED',
  PROFILE_NAME_REQUIRED: 'PROFILE_NAME_REQUIRED',
  OTP_INVALID: 'OTP_INVALID',
  OTP_EXPIRED: 'OTP_EXPIRED',
  OTP_MAX_ATTEMPTS: 'OTP_MAX_ATTEMPTS',
  OTP_THROTTLED: 'OTP_THROTTLED',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  PHONE_ALREADY_EXISTS: 'PHONE_ALREADY_EXISTS',
  PASSWORD_WEAK: 'PASSWORD_WEAK',
  PASSWORD_REUSED: 'PASSWORD_REUSED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  REFRESH_TOKEN_INVALID: 'REFRESH_TOKEN_INVALID',
  SESSION_NOT_FOUND: 'SESSION_NOT_FOUND',

  // Wallet / Ledger (PHASE 3)
  WALLET_NOT_FOUND: 'WALLET_NOT_FOUND',
  WALLET_INSUFFICIENT_BALANCE: 'WALLET_INSUFFICIENT_BALANCE',
  WALLET_LOCKED: 'WALLET_LOCKED',
  WALLET_FROZEN: 'WALLET_FROZEN',
  WALLET_CLOSED: 'WALLET_CLOSED',
  WALLET_AMOUNT_INVALID: 'WALLET_AMOUNT_INVALID',
  WALLET_CURRENCY_MISMATCH: 'WALLET_CURRENCY_MISMATCH',
  WALLET_LIMIT_EXCEEDED: 'WALLET_LIMIT_EXCEEDED',
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_CONFLICT: 'IDEMPOTENCY_KEY_CONFLICT',
  TRANSACTION_NOT_FOUND: 'TRANSACTION_NOT_FOUND',
  TRANSACTION_ALREADY_REVERSED: 'TRANSACTION_ALREADY_REVERSED',
  TRANSACTION_NOT_REVERSIBLE: 'TRANSACTION_NOT_REVERSIBLE',
  LEDGER_IMBALANCE: 'LEDGER_IMBALANCE',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_EXPIRED: 'PAYMENT_EXPIRED',

  // Contest / fantasy (reserved — implemented in later phases)
  CONTEST_FULL: 'CONTEST_FULL',
  CONTEST_CLOSED: 'CONTEST_CLOSED',
  CONTEST_ALREADY_JOINED: 'CONTEST_ALREADY_JOINED',
  TEAM_INVALID: 'TEAM_INVALID',
  KYC_REQUIRED: 'KYC_REQUIRED',

  // Contest (PHASE 6)
  CONTEST_NOT_FOUND: 'CONTEST_NOT_FOUND',
  CONTEST_NOT_OPEN: 'CONTEST_NOT_OPEN',
  CONTEST_LOCKED: 'CONTEST_LOCKED',
  CONTEST_CANCELLED: 'CONTEST_CANCELLED',
  CONTEST_NOT_JOINABLE: 'CONTEST_NOT_JOINABLE',
  CONTEST_INVALID_STATUS_TRANSITION: 'CONTEST_INVALID_STATUS_TRANSITION',
  CONTEST_HAS_ENTRIES: 'CONTEST_HAS_ENTRIES',
  CONTEST_TEMPLATE_NOT_FOUND: 'CONTEST_TEMPLATE_NOT_FOUND',
  CONTEST_TEMPLATE_IN_USE: 'CONTEST_TEMPLATE_IN_USE',
  PRIZE_DISTRIBUTION_INVALID: 'PRIZE_DISTRIBUTION_INVALID',
  PRIZE_DISTRIBUTION_NOT_FOUND: 'PRIZE_DISTRIBUTION_NOT_FOUND',
  CONTEST_ENTRY_NOT_FOUND: 'CONTEST_ENTRY_NOT_FOUND',
  CONTEST_USER_ENTRY_LIMIT: 'CONTEST_USER_ENTRY_LIMIT',
  CONTEST_TEAM_ALREADY_JOINED: 'CONTEST_TEAM_ALREADY_JOINED',
  CONTEST_INVITE_CODE_REQUIRED: 'CONTEST_INVITE_CODE_REQUIRED',
  CONTEST_INVITE_CODE_INVALID: 'CONTEST_INVITE_CODE_INVALID',

  // Sports / Matches (PHASE 4)
  MATCH_NOT_FOUND: 'MATCH_NOT_FOUND',
  TEAM_NOT_FOUND: 'TEAM_NOT_FOUND',
  PLAYER_NOT_FOUND: 'PLAYER_NOT_FOUND',
  TOURNAMENT_NOT_FOUND: 'TOURNAMENT_NOT_FOUND',
  SPORT_NOT_SUPPORTED: 'SPORT_NOT_SUPPORTED',
  SYNC_PROVIDER_FAILED: 'SYNC_PROVIDER_FAILED',
  SYNC_ALREADY_IN_PROGRESS: 'SYNC_ALREADY_IN_PROGRESS',
  MATCH_NOT_LIVE: 'MATCH_NOT_LIVE',
  MATCH_LOCK_VIOLATED: 'MATCH_LOCK_VIOLATED',

  // Fantasy (PHASE 5)
  FANTASY_RULES_NOT_CONFIGURED: 'FANTASY_RULES_NOT_CONFIGURED',
  FANTASY_TEAM_NOT_FOUND: 'FANTASY_TEAM_NOT_FOUND',
  FANTASY_TEAM_LOCKED: 'FANTASY_TEAM_LOCKED',
  FANTASY_TEAM_INVALID: 'FANTASY_TEAM_INVALID',
  FANTASY_TEAM_LIMIT_REACHED: 'FANTASY_TEAM_LIMIT_REACHED',
  FANTASY_DRAFT_NOT_FOUND: 'FANTASY_DRAFT_NOT_FOUND',
  FANTASY_RULE_IN_USE: 'FANTASY_RULE_IN_USE',
  FANTASY_SCORING_RULE_NOT_FOUND: 'FANTASY_SCORING_RULE_NOT_FOUND',

  // Scoring + Leaderboard + Settlement (PHASE 7)
  SCORING_NOT_READY: 'SCORING_NOT_READY',
  SCORING_RULE_INACTIVE: 'SCORING_RULE_INACTIVE',
  SCORING_RECOMPUTE_FAILED: 'SCORING_RECOMPUTE_FAILED',
  FANTASY_POINTS_NOT_FOUND: 'FANTASY_POINTS_NOT_FOUND',
  LEADERBOARD_NOT_FOUND: 'LEADERBOARD_NOT_FOUND',
  LEADERBOARD_REBUILD_FAILED: 'LEADERBOARD_REBUILD_FAILED',
  CONTEST_NOT_SETTLEABLE: 'CONTEST_NOT_SETTLEABLE',
  CONTEST_ALREADY_SETTLED: 'CONTEST_ALREADY_SETTLED',
  CONTEST_SETTLEMENT_IN_PROGRESS: 'CONTEST_SETTLEMENT_IN_PROGRESS',
  CONTEST_SETTLEMENT_FAILED: 'CONTEST_SETTLEMENT_FAILED',
  PRIZE_ALLOCATION_OVERFLOW: 'PRIZE_ALLOCATION_OVERFLOW',
  RANK_NOT_FOUND: 'RANK_NOT_FOUND',
} as const;

export type ErrorCodeKey = keyof typeof ErrorCode;
export type ErrorCodeValue = (typeof ErrorCode)[ErrorCodeKey];
